### ISSUE TITLE
validate on k8s-core fails during auth file propagation

### ISSUE THREAD

**Issue by battlemidget** [charmed-kubernetes/jenkins#427]
```
09:57:05 =================================== FAILURES ===================================
09:57:05 ________________________________ test_validate _________________________________
09:57:05 Traceback (most recent call last):
09:57:05   File "/var/lib/jenkins/slaves/jenkins-slave-5/workspace/validate-vault-v1.13.x/jobs/integration/test_cdk.py", line 16, in test_validate
09:57:05     await validate_all(model, log_dir)
09:57:05   File "/var/lib/jenkins/slaves/jenkins-slave-5/workspace/validate-vault-v1.13.x/jobs/integration/logger.py", line 47, in wrapper
09:57:05     result = await f(*args, **kwargs)
09:57:05   File "/var/lib/jenkins/slaves/jenkins-slave-5/workspace/validate-vault-v1.13.x/jobs/integration/validation.py", line 37, in validate_all
09:57:05     await validate_auth_file_propagation(model)
09:57:05   File "/var/lib/jenkins/slaves/jenkins-slave-5/workspace/validate-vault-v1.13.x/jobs/integration/logger.py", line 47, in wrapper
09:57:05     result = await f(*args, **kwargs)
09:57:05   File "/var/lib/jenkins/slaves/jenkins-slave-5/workspace/validate-vault-v1.13.x/jobs/integration/validation.py", line 90, in validate_auth_file_propagation
09:57:05     await run_until_success(follower,
09:57:05 UnboundLocalError: local variable 'follower' referenced before assignment
```

/cc @tvansteenburgh

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1843318.
